// formatos.js
export const formatos = [
  {
    id: 1,
    nombre_formato: "Excel",
    extension: ".xlsx",
    descripcion: "Formato de hoja de cálculo Microsoft Excel",
    alias: ["excel", "hoja de calculo", "spreadsheet", "xls", "xlsx", "Word","Periódico","Avacom"],
    agregado_por: "sistema",
    agregado_en: "2025-11-20T18:30:31.186Z",
    actualizado_por: null,
    actualizado_en: "2025-11-20T18:30:31.186Z",
    estado: "activo",
  },
  {
    id: 2,
    nombre_formato: "Excel Legacy",
    extension: ".xls",
    descripcion: "Formato de Excel anterior a 2007",
    alias: ["excel antiguo", "excel viejo", "xls"],
    agregado_por: "sistema",
    agregado_en: "2025-11-20T18:30:31.186Z",
    actualizado_por: null,
    actualizado_en: "2025-11-20T18:30:31.186Z",
    estado: "activo",
  },
  {
    id: 3,
    nombre_formato: "CSV",
    extension: ".csv",
    descripcion: "Valores separados por comas",
    alias: ["csv", "comma separated", "separado por comas", "valores separados"],
    agregado_por: "sistema",
    agregado_en: "2025-11-20T18:30:31.186Z",
    actualizado_por: null,
    actualizado_en: "2025-11-20T18:30:31.186Z",
    estado: "activo",
  },
  {
    id: 4,
    nombre_formato: "JSON",
    extension: ".json",
    descripcion: "Notación de objetos JavaScript",
    alias: ["json", "javascript object notation"],
    agregado_por: "sistema",
    agregado_en: "2025-11-20T18:30:31.186Z",
    actualizado_por: null,
    actualizado_en: "2025-11-20T18:30:31.186Z",
    estado: "activo",
  },
  {
    id: 5,
    nombre_formato: "XML",
    extension: ".xml",
    descripcion: "Lenguaje de marcado extensible",
    alias: ["xml", "extensible markup"],
    agregado_por: "sistema",
    agregado_en: "2025-11-20T18:30:31.186Z",
    actualizado_por: null,
    actualizado_en: "2025-11-20T18:30:31.186Z",
    estado: "activo",
  },
  {
    id: 6,
    nombre_formato: "PDF",
    extension: ".pdf",
    descripcion: "Documento portable (solo consulta)",
    alias: ["pdf", "portable document", "documento portable", "acrobat"],
    agregado_por: "sistema",
    agregado_en: "2025-11-20T18:30:31.186Z",
    actualizado_por: null,
    actualizado_en: "2025-11-20T18:30:31.186Z",
    estado: "activo",
  },
  {
    id: 7,
    nombre_formato: "SQL",
    extension: ".sql",
    descripcion: "Script de base de datos",
    alias: ["sql", "base de datos", "database", "script sql"],
    agregado_por: "sistema",
    agregado_en: "2025-11-20T18:30:31.186Z",
    actualizado_por: null,
    actualizado_en: "2025-11-20T18:30:31.186Z",
    estado: "activo",
  },
  {
    id: 8,
    nombre_formato: "TXT",
    extension: ".txt",
    descripcion: "Archivo de texto plano",
    alias: ["txt", "texto", "text", "plano", "plain text"],
    agregado_por: "sistema",
    agregado_en: "2025-11-20T18:30:31.186Z",
    actualizado_por: null,
    actualizado_en: "2025-11-20T18:30:31.186Z",
    estado: "activo",
  },
  {
    id: 9,
    nombre_formato: "Shapefile",
    extension: ".shp",
    descripcion: "Formato de datos geoespaciales",
    alias: ["shp", "shapefile", "shape", "geoespacial", "gis"],
    agregado_por: "sistema",
    agregado_en: "2025-11-20T18:30:31.186Z",
    actualizado_por: null,
    actualizado_en: "2025-11-20T18:30:31.186Z",
    estado: "activo",
  },
  {
    id: 10,
    nombre_formato: "GeoJSON",
    extension: ".geojson",
    descripcion: "Formato JSON para datos geográficos",
    alias: ["geojson", "geo json", "geografico json"],
    agregado_por: "sistema",
    agregado_en: "2025-11-20T18:30:31.186Z",
    actualizado_por: null,
    actualizado_en: "2025-11-20T18:30:31.186Z",
    estado: "activo",
  },
];